version: '3'
services:
  rabbit:
    container_name: boomcover_rabbit
    restart: always
    image: 'rabbitmq:alpine'
    networks:
      - backend
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBIT_USER}'
      RABBITMQ_DEFAULT_PASS: '${RABBIT_PASSWORD}'
  db:
    container_name: boomcover_mysql
    restart: always
    image: 'mysql:5.7'
    networks:
      - backend
    volumes:
      - './docker/db-data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
  nginx:
    container_name: boomcover_nginx
    image: 'nginx:1.12.1'
    restart: always
    volumes:
      - './public:/usr/src/app/public'
      - './landing:/usr/src/app/landing'
      - './docker/keys/${LANDING_HOST}/fullchain.pem:/etc/nginx/certs/${LANDING_HOST}.crt'
      - './docker/keys/${LANDING_HOST}/privkey.pem:/etc/nginx/certs/${LANDING_HOST}.key'
      - './docker/keys/${LANDING_HOST}/chain.pem:/etc/nginx/certs/${LANDING_HOST}.trusted'
      - './docker/keys/${HOST}/fullchain.pem:/etc/nginx/certs/${HOST}.crt'
      - './docker/keys/${HOST}/privkey.pem:/etc/nginx/certs/${HOST}.key'
      - './docker/keys/${HOST}/chain.pem:/etc/nginx/certs/${HOST}.trusted'
      - './protected/runtime:/usr/src/app/protected/runtime'
      - './nginx/nginx.ssl.template:/etc/nginx/nginx.template'
    command: '/bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf ''$${%s} '' $$v;done`''\" < /etc/nginx/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
    env_file:
      - ./.env
    networks:
      - backend
    ports:
      - '80:80'
      - '443:443'
      - '8081:8081'
    depends_on:
      - php
      - boomcover
  php:
    container_name: boomcover_php
    image: nanoninja/php-fpm
    restart: always
    networks:
      - backend
    volumes:
      - './landing:/usr/src/app/landing'
  boomcover:
    container_name: boomcover_app
    restart: always
    build: .
    env_file:
      - ./.env
    volumes:
      - './public:/usr/src/app/public'
      - './protected/covers/data:/usr/src/app/protected/covers/data'
      - './protected/runtime:/usr/src/app/protected/runtime'
    networks:
      - backend
    depends_on:
      - db
      - rabbit
  phpmyadmin:
    container_name: boomcover_phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    networks:
      - backend
    ports:
      - '8080:80'
    environment:
      MYSQL_USERNAME: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - db
networks:
  backend: null
